name: 05 - 1 - Event Filters and Activity Types
on:
    workflow_dispatch:
jobs:
    echo:
       runs-on: ubuntu-latest
       steps:
           - name: Dump GitHub context
             run: echo "${{ toJson(github) }}"
           - name: "How it got merged"
             run: echo "Running whenever a PR is opened or synchronized AND base branch is main"
           - name: This is value
             run: |
                  BRANCH_NAME="${{github.ref}}"
                  BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's|^refs/heads/||')
                  echo "Branch name is: $BRANCH_NAME"


